[toolchain]
anchor_version = "0.31.1"

[features]
resolution = false
seeds = false
skip-lint = false

[programs.localnet]
token_distributor = "2Ab8No85xrnnd2rFamKjQqGAK6Qu9EQ4eEh59oaZEPBL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "https://api.devnet.solana.com"
# cluster = "https://api.testnet.solana.com"
# cluster = "https://api.mainnet-beta.solana.com"
# cluster = "${SOLANA_CLUSTER:=localnet}" # if not set SOLANA_CLUSTER, default to use localnet

wallet = "~/.config/solana/id.json"

[scripts]
# test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token_distributor.ts"
test = "RUST_LOG=info yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token_distributor_litesvm.ts"


[test.validator]
bind_address = "0.0.0.0"
url = "http://localhost:3000"
# url = "${SOLANA_CLUSTER:=localnet}"
ledger = ".anchor/test-ledger"
rpc_port = 8899
faucet_port = 9901
